/**
 * Every card's colour identity, frozen from the retired MTG-style derivation
 * (its Essence Cost pips) on 2026-10-09 so that swapping in the poker game
 * changes no card's colour. Matches the live `cards.essence_types` column.
 *
 * Cards printed after the freeze fall back to `fallbackColors` in cardpool.ts.
 */
import type { Color } from './colors';

export const FROZEN_COLORS: Record<string, Color[]> = {
  absolute_eruption: ['Light'],
  abyssal_dragonfish: ['Light'],
  abyssal_pathway: ['Ember'],
  admiral_iron_claw: ['Root'],
  alchemists_vial_belt: [],
  algal_veil: ['Light'],
  amber_sphere: ['Gale'],
  amethyst_starfish: ['Ember'],
  anchor_graveyard: ['Gale'],
  anemone_weaver: ['Root'],
  apex_nanite_shinobi: ['Gale', 'Shadow'],
  apocalypse_beam: ['Shadow'],
  ash_shaper_mystic: ['Ember'],
  ashbreath_witch: ['Tide'],
  ashen_circle_rite: ['Ember'],
  ashhound_pack: ['Gale'],
  astral_shoal: [],
  avatar_of_the_abyss: ['Shadow', 'Void'],
  baron_von_swine: ['Root', 'Void'],
  barrier_projection_field: ['Shadow'],
  binding_slab: ['Void'],
  bioluminescent_tide: ['Ember', 'Light'],
  black_coral_thicket: ['Light'],
  black_glass_altar: ['Shadow'],
  black_smoker: ['Shadow'],
  blackspire_obelisk: ['Tide'],
  bladetail_symbiont: ['Void'],
  blight_snarler: ['Shadow', 'Void'],
  blind_allegiance: ['Shadow'],
  blind_archivist: ['Void'],
  blind_colossus: ['Tide'],
  blood_moon_descent: ['Ember', 'Void'],
  blossom_veiled_refuge: ['Shadow'],
  blue_ringed_octopus: ['Void'],
  bone_splinter_quill: ['Light'],
  bone_throne: ['Void'],
  bone_white_forest: ['Gale'],
  bonemasked_wanderer: ['Tide'],
  boneplate_sentinel: ['Shadow'],
  bound_leviathan: ['Tide'],
  brass_whale: ['Root'],
  bubble_harvest: ['Ember'],
  butterflyfish_school: ['Root'],
  caldera_harvest_works: ['Tide'],
  cavernous_watcher: ['Gale'],
  celestial_attunement: ['Light'],
  cervine_channeler: ['Ember', 'Light'],
  chalice_of_quicksilver: ['Ember', 'Gale'],
  charred_frilled_shark: ['Light'],
  chrome_barracuda: ['Light'],
  chrono_tide: ['Void'],
  chrysalis_of_the_departed: ['Tide', 'Light'],
  cinder_mite: ['Tide'],
  clam_chest: ['Gale'],
  clash_of_titans: ['Shadow'],
  clawblade_greatsword: ['Shadow'],
  clockwork_nautilus: ['Ember'],
  cold_fire_volcano: ['Shadow'],
  constellation_crabs: ['Root'],
  consuming_ash_cloud: ['Gale'],
  copper_nautilus: ['Void'],
  coral_cathedral: ['Void'],
  coral_collapse: [],
  corrosive_bloom: ['Tide', 'Light'],
  cracked_wastes: ['Shadow'],
  crimson_tube_worms: ['Shadow'],
  crimson_vector_commander: ['Ember', 'Light'],
  crown_of_the_reef: ['Tide'],
  crowned_manatee: ['Root', 'Void'],
  cruel_effervescence: ['Ember'],
  crystalline_flower: ['Ember'],
  crystalline_metropolis: ['Ember'],
  curse_of_the_ruby_tide: ['Gale'],
  deceptive_angler: ['Gale'],
  diamond_anchor: ['Ember', 'Gale'],
  dissolving_persona: ['Void'],
  diver_s_lantern: ['Ember'],
  dr_aries_chief_biogeneticist: ['Tide', 'Root'],
  dragon_amid_the_stars: ['Light'],
  dragonclaw_gauntlet: [],
  driftwood_harp: ['Ember'],
  eel_s_weave: ['Shadow', 'Void'],
  ember_whisperer: ['Root'],
  emerald_turtle: ['Ember'],
  ethereal_sea_witch: ['Tide', 'Light'],
  familiar_in_the_dark: ['Gale', 'Shadow'],
  fangblade_dagger: ['Void'],
  fayes_true_face: ['Ember', 'Void'],
  femur_catapult: ['Ember'],
  filigree_nautilus: ['Void'],
  fissure_gas_bunker: ['Gale'],
  flash_freeze: ['Tide'],
  flesh_to_bone: ['Void'],
  flickering_sea_pens: ['Root'],
  floating_jellyfish: ['Gale'],
  fossil_fangtrap: [],
  frosted_isopod: ['Gale', 'Shadow'],
  galaxy_jellyfish: [],
  galleon_shipwreck: ['Ember'],
  gearbone_sentinel: ['Gale', 'Shadow'],
  gearbone_strider: ['Light'],
  ghost_tunicate: ['Void'],
  glacier_shark: [],
  glass_kelp_forest: ['Gale'],
  glass_shrimp: ['Ember', 'Gale'],
  glass_squid: ['Tide'],
  glassmote_construct: ['Void'],
  glowing_glyph_tablet: ['Tide', 'Root'],
  glowing_manta: ['Ember'],
  glowing_sea_spider: ['Ember'],
  goldstream_conjurer: ['Tide'],
  gossamer_jellyfish: ['Gale', 'Shadow'],
  graftbone_colossus: ['Tide', 'Root'],
  grafted_steamwings: ['Void'],
  grit_and_halftones: ['Shadow', 'Void'],
  gulper_eel: ['Ember', 'Void'],
  half_faded_shade: ['Root', 'Void'],
  hammerhead_silhouette: ['Void'],
  handed_squid: ['Root'],
  haunted_submarine: ['Tide'],
  heart_coral: ['Root'],
  heart_of_the_thermal_grid: ['Shadow'],
  helix_swarm: ['Void'],
  helmet_hermit: ['Shadow'],
  hive_power_cell: ['Light'],
  hollow_eyed_pyromancer: ['Gale'],
  hollow_suit: ['Tide', 'Light'],
  iron_scaled_snail: ['Ember'],
  isle_of_shells: ['Shadow'],
  isle_of_the_ancients: ['Shadow'],
  jagged_dragonfang_blade: ['Shadow'],
  jarred_sunspark: ['Root', 'Void'],
  jawbone_span: ['Root'],
  kinetic_anchor_monolith: ['Ember'],
  kinetic_overflow: ['Ember', 'Gale'],
  kinetic_piercer: ['Shadow'],
  kinetic_siphon_swarm: ['Root'],
  kinetic_storage_gauntlet: ['Shadow'],
  kinetix_blacksite_cavern: ['Root'],
  kinetix_enforcer: ['Shadow'],
  kraken_s_monolith: ['Tide', 'Root'],
  krill_constellation: ['Light'],
  kunoichi_of_the_magma_rings: ['Ember'],
  lace_lionfish: [],
  legendary_diver: ['Ember', 'Gale'],
  levitating_coven: ['Gale'],
  light_seahorse: ['Ember'],
  locust_veil: ['Void'],
  magma_conduit_network: ['Root'],
  magma_phase_infiltrator: ['Shadow'],
  magma_ring_adept: ['Shadow'],
  mandarin_dragonet: ['Ember'],
  map_pearl: ['Light'],
  marble_reef_shark: ['Ember', 'Light'],
  masked_fume_walker: ['Void'],
  mausoleum_edge: ['Shadow', 'Void'],
  melted_hollow: ['Root'],
  mer_king: ['Tide', 'Root'],
  mer_warrior: ['Shadow'],
  merfolk_ritual: ['Light'],
  mermaid_statue: ['Light'],
  mesozoic_exchange_student: ['Void'],
  micro_drone_immolation: ['Tide'],
  mirror_hatchetfish: ['Root'],
  mist_ghost_ship: ['Light'],
  molten_camo_weave: ['Gale'],
  nanite_culture_lab: ['Void'],
  nanite_division_marshal: ['Void'],
  nanite_purge_protocol: ['Gale'],
  nanite_shock_trooper: ['Ember', 'Void'],
  narwhal_staff: ['Tide', 'Light'],
  nebula_clutch: ['Tide'],
  nebula_snail: ['Gale'],
  needle_seamstress: ['Void'],
  neon_moray: ['Shadow'],
  neon_phantom_assassin: ['Ember', 'Light'],
  obsidian_altar: ['Light'],
  obsidian_bore_site: ['Tide'],
  obsidian_dice: ['Shadow'],
  obsidian_golem: [],
  obsidian_scalpel: ['Tide'],
  obsidian_swordfish: ['Light'],
  obsidian_trident: ['Tide'],
  ossuary_vault: ['Ember'],
  outrun_horizon: ['Void'],
  overseer_optic: ['Tide'],
  pearl_of_the_deep: ['Tide', 'Root'],
  perpetual_dynamo: ['Void'],
  petrified_ribs_citadel: ['Tide'],
  phantom_dumbo: ['Gale', 'Shadow'],
  phantom_squadron: ['Tide'],
  phantom_whale: ['Void'],
  phantom_wing_leaper: ['Ember'],
  phosphor_lich: ['Shadow'],
  playful_otters: ['Void'],
  polished_waystone: ['Gale'],
  pop_culture_commando: ['Void'],
  porcelain_lobster: ['Tide', 'Root'],
  pufferfish_lantern: ['Gale'],
  pulsating_clam: ['Ember'],
  pulsing_heartstone: ['Tide'],
  purple_lensed_goggles: ['Gale'],
  pyroproof_vanguard: ['Root'],
  research_fleet: ['Root'],
  resonant_shuriken: ['Tide'],
  ribbone_longbow: ['Tide', 'Root'],
  ribcage_titan: ['Shadow', 'Void'],
  ribvault_cathedral: ['Root'],
  ruin_scavenger: ['Ember', 'Void'],
  ruinwalker_overseer: ['Root', 'Void'],
  rune_etched_tablet: ['Shadow'],
  rune_ignition: ['Tide'],
  runeforge_smith: ['Root'],
  ruthless_succession: ['Tide'],
  sand_portal: ['Ember'],
  sand_waterfall: ['Light'],
  sandstorm_effigy: ['Tide'],
  sardine_vortex: ['Shadow'],
  scale_butterfly: ['Root'],
  scallop_map: ['Tide', 'Root'],
  scorched_bone_standard: ['Tide', 'Root'],
  seabed_mandala: ['Tide'],
  secret_lair: ['Shadow'],
  shark_gathering: ['Ember'],
  shattered_horizon_protagonist: ['Tide', 'Root'],
  shatterline: ['Root'],
  shimmering_statue: ['Void'],
  shinobi_operations_base: ['Light'],
  silver_chimera: ['Tide', 'Light'],
  skeletal_steed_rider: ['Shadow'],
  skull_cathedral: ['Void'],
  skyborne_skeleton_dragon: ['Root'],
  skydark_locust_host: ['Shadow'],
  slate_scaled_serpent: ['Tide', 'Root'],
  smokeveil_striketeam: ['Root', 'Void'],
  sonic_shatter: ['Tide'],
  sovereign_of_the_dying_star: ['Ember', 'Void'],
  sovereign_spires_of_arrak_zul: ['Light'],
  sparkling_meadow: ['Light'],
  spectral_leviathan: ['Gale'],
  sphere_pufferfish: ['Tide'],
  stag_of_the_cosmic_pyre: ['Ember', 'Void'],
  star_patterned_manta: ['Shadow'],
  stone_bubbles: ['Void'],
  stone_hand: ['Gale'],
  stormcaller_adept: ['Ember'],
  submerged_archives: ['Tide'],
  submerged_starfall: ['Light'],
  submerged_statue: ['Void'],
  submerged_temple: ['Shadow'],
  sunken_archive: ['Root'],
  sunken_bounty: ['Void'],
  sunken_meadow: ['Shadow'],
  sunken_timepiece: ['Tide', 'Light'],
  swaying_garden: ['Root'],
  swirling_ink_cloud: ['Void'],
  symbiotic_scan_swarm: ['Gale'],
  tailbone_throne: ['Root'],
  tang_s_refuge: ['Tide', 'Root'],
  tangled_seahorses: ['Tide'],
  tattooed_sovereign: ['Tide'],
  tectonic_rift: [],
  tethered_orbs: ['Void'],
  the_abyssal_gate: ['Tide'],
  the_chimney_snacker: ['Light'],
  the_descent: ['Gale'],
  the_floating_eye: ['Tide'],
  the_garden_variety_glock: ['Tide', 'Light'],
  the_locksmiths_regret: ['Tide'],
  the_mirrored_trench: ['Gale'],
  the_pier_side_menace: ['Void'],
  the_taking: ['Gale', 'Shadow'],
  the_wolf_of_wall_street: ['Void'],
  thornfang_vine: [],
  threefold_bone_shield: ['Shadow'],
  titan_of_the_trench: ['Shadow'],
  topographic_behemoth: ['Root'],
  towering_tsunami: ['Root'],
  trench_gateway: ['Shadow'],
  urnbearer_of_blight: ['Gale'],
  vampire_squid: ['Shadow'],
  vector_blade_captain: ['Gale'],
  victorian_helmet: ['Root'],
  violet_haze_kunoichi: ['Root'],
  vlad_from_accounting: ['Tide', 'Light'],
  void_mother: ['Shadow', 'Void'],
  volcanic_crab: ['Gale'],
  volcanic_nanite_core: ['Gale'],
  wasteland_aberration: ['Root'],
  wasteland_rupture: ['Void'],
  whale_fall_ceremony: ['Root'],
  whelpbone_hatchling: ['Gale'],
  where_the_deep_meets_the_sky: ['Ember', 'Light'],
  wingbone_horror: ['Shadow'],
  worm_brain_host: [],
  wraithlight_lantern: [],
  zen_decay: ['Ember', 'Void'],
};
